### PR TITLE
Use Unix and Unix-like instead of Linux and Unix

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
But we are on Linux and not unix.

**Comment by rbuj** [comment]
OpenIndiana uses MATE Desktop. https://wiki.openindiana.org/oi/MATE+1.18+Desktop
OpenIndiana - OS family: Unix (SVR4 = System V Release 4, aka System V.4).

You can also use MATE Desktop on FreeBSD: https://www.freebsd.org/ports/mate.html
FreeBSD - OS family: Unix-like (BSD)

You can also use MATE Desktop on some GNU/Linux distributions (Fedora, Ubuntu, Debian, ...).
GNU/Linux distributions - OS family: Unix-like

**Comment by raveit65** [comment]
Let's wait what other team member think about.

**Comment by lukefromdc** [comment]
I think this idea is fine so long as MATE as a whole builds on BSD's etc. As I recall we still use a conditional check to only build the CPUfreq applet when building over Linux,  and Linux is a subset of "Unix-like" so I see no problem with this change.

**Comment by rbuj** [comment]
We can use the convetions of FHS 3.0:

- Unix-like operating systems (instead of Linux or BSD, and remove Unix). Abstract: http://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html
- listing of directories, or symbolic links to directories, that are directly under the root (instead of "listing of common directories that are directly under the root"). http://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#requirements.

At the end of the section, for example, we can add a note: More info available at http://refspecs.linuxfoundation.org/fhs.shtml

**Comment by rbuj** [comment]
Virtual filesystem in Unix-like operating systems #18

**Comment by alexarnaud** [comment]
I don't think removing Linux is a good idea because the beginner could know Linux and not Unix-like. If we keep Linux and Unix I don't think user of BSD or other system would find confusion but beginner wouldn't be able to understand what Unix means.

Best regards,
Alex.

**Comment by rbuj** [comment]
Ok. We can use "Linux and other Unix-like operating systems", 1st paragraph at https://mate-desktop.org/

**Comment by rbuj** [comment]
@alexarnaud @raveit65, please add your comments in #18 
Do not remove Linux, improve enumeration of inode metadata https://github.com/mate-desktop/mate-user-guide/pull/18/commits/f6a4353f4fb49d6eeeb45e485ca11d3609fa08d7

**Pull request closed without merging**
