### PR TITLE
Remove unused screenshots

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
This now works, both mate-panel and caja help come up fine and I didn't notice anything missing(though I have not poked around it recently enough to notice anything subtle.)

**Review by raveit65 — COMMENTED** [review]
Can you please check if images not belongs to other packages?
Eg. pluma
```
[rave@satellite mate-user-guide]$ grep -nr pluma_window.png ../pluma/help/C/*
../pluma/help/C/index.docbook:289:				  <imagedata fileref="figures/pluma_window.png" format="PNG"/>
```
Or is this image shipped by pluma package?
I stopped at this point to **grep** in other packages, so maybe there are more images which shouldn't removed

**Comment by rbuj** [comment]
Ok. We can use "Linux and other Unix-like operating systems", 1st paragraph at https://mate-desktop.org/

**Comment by rbuj** [comment]
WIP

**Comment by sc0w** [comment]
@raveit65 

I confirm pluma isn't affected by this PR

Pluma have its own file `pluma_window.png`

**Comment by rbuj** [comment]
This script finds all C/figures/*.png files in MATE project which don't have their md5 in any pot file.
The pot files should exist and they should have the correct md5 for the png file.
<pre>
#!/bin/bash
# ---------------------------------------------------------------------------
# Copyright 2018, Robert Buj <rbuj@fedoraproject.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.
# ---------------------------------------------------------------------------

rm -f mate-desktop.list
# get repo list
for i in {1..2}; do
  curl -s "https://api.github.com/orgs/mate-desktop/repos?page=$i" | jq '.[] | {name, git_url}' | xargs -L4 | perl -pe 's/^\{ name\: (.*), git_url: (.*) \}$/\1 \2/g' >> mate-desktop.list
done

# clone repos
while read line; do read -ra entries <<<"$line"; git clone ${entries[1]}; done < ./mate-desktop.list

# md5 database for png files
find . -type f -regex ".*/C/figures/.*\.png" -exec md5sum {} + > md5_db.txt
find . -type f -name *.pot -exec grep -F "md5" {} + > pot_db.txt

while read md5_png_file; do
  read -ra actual_md5_png_file <<<"$md5_png_file"

  # search for md5 in pot files
  if grep -Fq $actual_md5_png_file pot_db.txt
  then
    # code if found
    found_md5=1
  else
    echo $md5_png_file | awk '{print $2}'
  fi
done < md5_db.txt
</pre>
./mate-applets/accessx-status/docs/C/figures/accessx_bounce-keys.png
./mate-applets/accessx-status/docs/C/figures/accessx_mouse-keys.png
./mate-applets/accessx-status/docs/C/figures/accessx_slow-keys.png
./mate-applets/accessx-status/docs/C/figures/accessx-status-applet.png
./mate-applets/accessx-status/docs/C/figures/accessx-status-disabled.png
./mate-applets/accessx-status/docs/C/figures/accessx_sticky-altGr-key.png
./mate-applets/accessx-status/docs/C/figures/accessx_sticky-ctrl-key.png
./mate-applets/accessx-status/docs/C/figures/accessx_sticky-keys.png
./mate-applets/accessx-status/docs/C/figures/accessx_sticky-meta-key.png
./mate-applets/accessx-status/docs/C/figures/accessx_sticky-shift-key.png
./mate-applets/accessx-status/docs/C/figures/accessx_sticky-windows-key.png
./mate-applets/battstat/docs/C/figures/battstat-applet-expanded.png
./mate-applets/battstat/docs/C/figures/battstat-applet.png
./mate-applets/battstat/docs/C/figures/battstat-credits-hal.png
./mate-applets/battstat/docs/C/figures/battstat-preferences.png
./mate-applets/battstat/docs/C/figures/context-menu.png
./mate-applets/charpick/help/C/figures/charpalette_applet.png
./mate-applets/charpick/help/C/figures/charpalette_chargroup.png
./mate-applets/charpick/help/C/figures/charpick_characters.png
./mate-applets/charpick/help/C/figures/charpick-preferences.png
./mate-applets/cpufreq/help/C/figures/cpufreq-100.png
./mate-applets/cpufreq/help/C/figures/cpufreq-25.png
./mate-applets/cpufreq/help/C/figures/cpufreq-50.png
./mate-applets/cpufreq/help/C/figures/cpufreq-75.png
./mate-applets/cpufreq/help/C/figures/cpufreq-applet.png
./mate-applets/cpufreq/help/C/figures/cpufreq-applet-preferences.png
./mate-applets/cpufreq/help/C/figures/cpufreq-applet-preferences-smp.png
./mate-applets/cpufreq/help/C/figures/cpufreq-applet-selector-both.png
./mate-applets/cpufreq/help/C/figures/cpufreq-applet-selector.png
./mate-applets/drivemount/help/C/figures/drivemount-applet_eject.png
./mate-applets/drivemount/help/C/figures/drivemount-applet_example.png
./mate-applets/drivemount/help/C/figures/drivemount-applet_mount.png
./mate-applets/drivemount/help/C/figures/drivemount-applet_open.png
./mate-applets/drivemount/help/C/figures/drivemount-applet_status.png
./mate-applets/geyes/docs/C/figures/geyes_applet.png
./mate-applets/mateweather/docs/C/figures/mateweather_applet.png
./mate-applets/mateweather/docs/C/figures/mateweather-details.png
./mate-applets/mateweather/docs/C/figures/mateweather-menu-prefs.png
./mate-applets/mateweather/docs/C/figures/mateweather-prefs-general.png
./mate-applets/mateweather/docs/C/figures/mateweather-prefs-locations.png
./mate-applets/mateweather/docs/C/figures/stock_weather-cloudy.png
./mate-applets/mateweather/docs/C/figures/stock_weather-few-clouds.png
./mate-applets/mateweather/docs/C/figures/stock_weather-fog.png
./mate-applets/mateweather/docs/C/figures/stock_weather-night-clear.png
./mate-applets/mateweather/docs/C/figures/stock_weather-night-few-clouds.png
./mate-applets/mateweather/docs/C/figures/stock_weather-showers.png
./mate-applets/mateweather/docs/C/figures/stock_weather-snow.png
./mate-applets/mateweather/docs/C/figures/stock_weather-storm.png
./mate-applets/mateweather/docs/C/figures/stock_weather-sunny.png
./mate-applets/multiload/docs/C/figures/multiload-preferences.png
./mate-applets/multiload/docs/C/figures/system-monitor-applet_window.png
./mate-applets/multiload/docs/C/figures/system_monitor.png
./mate-applets/netspeed/help/C/figures/details.png
./mate-applets/netspeed/help/C/figures/ethernet.png
./mate-applets/netspeed/help/C/figures/eth_sum_48.png
./mate-applets/netspeed/help/C/figures/loopback.png
./mate-applets/netspeed/help/C/figures/netspeed_applet.png
./mate-applets/netspeed/help/C/figures/plip.png
./mate-applets/netspeed/help/C/figures/ppp.png
./mate-applets/netspeed/help/C/figures/settings.png
./mate-applets/netspeed/help/C/figures/wavelan.png
./mate-applets/stickynotes/docs/C/figures/stickynote-right-menu-lock.png
./mate-applets/stickynotes/docs/C/figures/stickynote-right-menu-new.png
./mate-applets/stickynotes/docs/C/figures/stickynotes_applet.png
./mate-applets/stickynotes/docs/C/figures/stickynotes-note-prefs.png
./mate-applets/stickynotes/docs/C/figures/stickynotes-prefs.png
./mate-applets/trashapplet/docs/C/figures/trash-applet.png
./mate-panel/help/mate-clock/C/figures/clock_applet.png
./mate-panel/help/mate-fish/C/figures/fish_applet.png
./mate-power-manager/help/C/figures/applet-brightness.png
./mate-power-manager/help/C/figures/applet-inhibit.png
./mate-power-manager/help/C/figures/gpm-cell-capacity.png
./mate-power-manager/help/C/figures/gpm-charged.png
./mate-power-manager/help/C/figures/gpm-critical.png
./mate-power-manager/help/C/figures/gpm-low.png
./mate-power-manager/help/C/figures/gpm-prefs-ac.png
./mate-power-manager/help/C/figures/gpm-prefs-battery.png
./mate-power-manager/help/C/figures/gpm-prefs-general.png
./mate-power-manager/help/C/figures/gpm-stats-graph.png
./mate-power-manager/help/C/figures/gpm-suspend-problem.png
./mate-power-manager/help/C/figures/gpm-unplugged.png
./mate-power-manager/help/C/figures/gs-prefs.png
./mate-sensors-applet/help/C/figures/applet_in_panel.png
./mate-system-monitor/help/C/figures/addColumn.png
./mate-system-monitor/help/C/figures/changePriority.png
./mate-system-monitor/help/C/figures/colorPanel.png
./mate-system-monitor/help/C/figures/columnContextMenu.png
./mate-system-monitor/help/C/figures/mate-system-monitor_window.png
./mate-system-monitor/help/C/figures/memoryMaps.png
./mate-system-monitor/help/C/figures/moreInfo.png
./mate-system-monitor/help/C/figures/processListing.png
./mate-system-monitor/help/C/figures/sortButton.png
./mate-system-monitor/help/C/figures/sortMenu2.png
./mate-system-monitor/help/C/figures/sortMenu.png
./mate-system-monitor/help/C/figures/systemMonitor.png
./mate-system-monitor/help/C/figures/viewMenu.png
./mate-terminal/help/C/figures/mate-terminal-default.png
./mate-terminal/help/C/figures/mate-terminal-tabbed.png
./mate-user-guide/mate-user-guide/C/figures/caja_computer_launcher.png
./mate-user-guide/mate-user-guide/C/figures/caja_sampleemblem1_icon.png
./mate-user-guide/mate-user-guide/C/figures/caja_sampleemblem2_icon.png
./mate-user-guide/mate-user-guide/C/figures/caja_sampleemblem3_icon.png
./mate-user-guide/mate-user-guide/C/figures/caja_sampleemblem_icon.png
./mate-user-guide/mate-user-guide/C/figures/caja_samplesymlink_icon.png
./mate-user-guide/mate-user-guide/C/figures/caja_starthere_launcher.png
./mate-user-guide/mate-user-guide/C/figures/com_file_manager_menu.png
./mate-user-guide/mate-user-guide/C/figures/mate_panel.png
./mate-user-guide/mate-user-guide/C/figures/pluma_window.png
./mate-user-guide/mate-user-guide/C/figures/screenshot_button.png
./mate-user-guide/mate-user-guide/C/figures/titlebar_anno_window.png
./mate-user-guide/mate-user-guide/C/figures/typical_menu.png
./mate-user-guide/mate-user-guide/C/figures/window_list_applet.png
./mate-user-guide/mate-user-guide/C/figures/window_list_group_applet.png
./mate-user-share/help/C/figures/file-sharing-preferences.png
./mate-user-share/help/C/figures/receiving-over-bluetooth.png
./mate-user-share/help/C/figures/sharing-over-bluetooth.png
./mate-user-share/help/C/figures/sharing-over-the-network.png
./pluma/help/C/figures/pluma_format_bold.png
./pluma/help/C/figures/pluma_format_italic.png
./pluma/help/C/figures/pluma_format_strikethrough.png
./pluma/help/C/figures/pluma_format_underline.png

**Review by sc0w — CHANGES_REQUESTED** [review]
mate-user-guide doesn't work anymore with this PR for me:

screenshot at 2018-09-27 05-05-11

**Comment by lukefromdc** [comment]
How exactly did you build this? Did you start with a tarball downloaded from the branch, a git pull into your local repo with a merge commit, or a git pull and rebase? When I pulled this it rebased clean, with the reverted merge commit not containing any changed files. Any chance you used the previous branch?

If not, we once again have this failing in at least one case.

**Comment by raveit65** [comment]
@sc0w 
Do you have this commit from master in your local git history?
https://github.com/mate-desktop/mate-user-guide/commit/f7d047aa8f433977cd10a5d16ca1c228008a20e3
After checkout this branch from PR do a `git rebase master`

**Comment by raveit65** [comment]
Btw. help from applets of mate-applets aren't translated by transifex. I will add them to config today.

**Review by raveit65 — APPROVED** [review]
Works fine, i didn't find any missing image for caja ,panel ,pluma or screenshot in the guide.
Distcheck runs fine and i can executing the guide with eg.
env LANG=us_US.UTF-8 yelp help:mate-user-guide

**Comment by sc0w** [comment]
I just builded and installed the .deb packages

I investigated it, and this is the culprit commit (not related to this PR):

https://github.com/rbuj/mate-user-guide/commit/67e21ea1fadac11b2aef67e4744901706295a5c0

**Comment by sc0w** [comment]
aha, seems since the mentioned commit, now it works with:

`yelp help:mate-user-guide-content`

instead:

`yelp help:mate-user-guide`

**Comment by raveit65** [comment]
@sc0w 
Yes , and i fixed it 
So  can you approve the PR?
You only need to do `git rebase master` in this branch.
Than my fixing commit is in this branch too.

**Comment by raveit65** [comment]
I did  a mistake and changed 
HELP_ID = mate-user-guide
to
HELP_ID = mate-user-guide-content
in makefile 
This i have reverted here 
https://github.com/mate-desktop/mate-user-guide/commit/f7d047aa8f433977cd10a5d16ca1c228008a20e3#diff-dbd687f202c1541cd073d3e9e6008dc9L3

**Comment by sc0w** [comment]
ah ok, understood :)

**Review by sc0w — APPROVED** [review]

**Pull request merged**
