### PR TITLE
dconf settings storage system

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by lukefromdc** [comment]
What is this supposed to do? I see the commit but not its function here

**Review by sc0w — APPROVED** [review]
It seems to be fine

This PR can be tested with:

$ yelp help:mate-user-guide/mate-dconf-intro

**Review by lukefromdc — COMMENTED** [review]
Oh yah-that's a nice addition.

 One issue though is the location of the dconf databases. In some systems (I am on Debian Unstable) there are only the databases in ~/.config/dconf. On my system the only thing in /etc/dconf/db is gdm.d (I normally use lightdm but gdm is installed), and that contains a single plain text file (90-debian-settings) that may be left over from an old version as it was last changed in 2014. There is nothing else is in that folder or in /etc/deconf here. . All of the other deconf files I can find are the ones in ~/config .

Thus this line is sometimes wrong:
`
All dconf profiles are stored in the /etc/dconf/profile folder`

And this is in:

```
dconf uses several database files in GVDB binary format, one database per file. A dconf profile consists of a single file, in plain text format, which contains a list of database files in GVDB format. All dconf profiles are stored in the /etc/dconf/profile folder. Example of content for the user profile (/etc/dconf/profile/user file):
user-db: user
system-db: local
system-db: site
system-db: distro
The previous dconf profile contains 4 GVDB files, one per line.
user is the name of the user's databases. They are usually located in the ~/.config/dconf folder
local, site and distro are system databases. They are usually located in the /etc/dconf/db folder
Each one of these databases store key-value pairs using a hash map data structure, which can map string keys to GVariant values in a way that is extremely efficient for lookups. The lookup preference is determined by the order of appearance in the dconf profile file, user's databases have the highest preference in the previous dconf profile example. The keys from multiple configuration sources coexist in a logical tree structure. MATE Desktop key-value hashmap entries are under the /org/mate logical node, which are usually stored in user's databases.
```

**Review by selectiveduplicate — COMMENTED** [review]
I agree with @lukefromdc about the location of dconf profiles- it varies. For example, on my system, I've noticed that I only have a "profile" file for ``ibus`` in the ``/etc/dconf/profile`` directory, and with that I also have ``ibus.d`` in ``/etc/dconf/db/`` directory. 

As per what I know, an environmental variable can specify a relative path to a "profile" file from the ``/etc/dconf/profile/`` directory, or the home directory of an user, such as the ``.config/dconf/`` directory.

I think it would be good to give a bit of "brief introduction" to a couple of key-terms in the beginning:
-  **GSettings**. 
-  **dconf** as in the configuration system and also the command-line utility ``dconf`` that is used to tinker with the **dconf** databases and
-  **gsettings** as in the command-line utility.

**Comment by lukefromdc** [comment]
We still have the 

`All dconf profiles are stored in the <filename class='directory'>/etc/dconf/profile</filename> folder.`

line, which should be be changed to something like

`All system dconf profiles are stored in the <filename class='directory'>/etc/dconf/profile</filename> folder.`

**Comment by rbuj** [comment]
/etc/dconf/profile contains user dconf profile, which is not a system dconf profile (e.g. system services). However, user dconf profile can include or not system databases (e.g. settings for Linux distros, like Fedora: system-db: distro).

REF: Profiles section - https://developer.gnome.org/dconf/unstable/dconf-overview.html

**Comment by lukefromdc** [comment]
/etc/dconf/profile does not exist on my system, which is based on Debian Unstable

**Comment by rbuj** [comment]
Last line in profiles section - https://developer.gnome.org/dconf/unstable/dconf-overview.html
> If the DCONF_PROFILE environment variable is unset and the "user" profile can not be opened, then the effect is as if the profile was specified by this file:
>
> user-db:user

**Comment by raveit65** [comment]
There is another dir.
`/var/run/user/1000/dconf/user`
If i like to clean a account i remove normally 2 files.
`/var/run/user/1000/dconf/user` and `~/.config/dconf/user`
But i can confirm that fedora follow specs and have `/etc/dconf/profile/user`.

Well, it's not the first time that distros don't follow upstream specs.

**Comment by raveit65** [comment]
Weird, the content of `~/.config/dconf/user` and `/etc/dconf/profile/user` is complete different.
Tested with `dconf dump / user >> test`
Edit:
`~/.config/dconf/user` contains all settings while `/etc/dconf/profile/user` contains only a few keys.

**Review by raveit65 — APPROVED** [review]
awesome,
very nice work with good examples how to use dconf/gsettings from command line.
It builds and runs fine.
Ready to  go

**Pull request merged**
