### PR TITLE
Migrate from intltool to gettext

### PR DESCRIPTION
**Pull request by yetist**
Please review and test.

### CODE REVIEW

**Comment by lukefromdc** [comment]
Travis shows a build error on Fedora 30 with other builds completing

**Comment by yetist** [comment]
@lukefromdc 

After restart job, all builds passed.

**Comment by raveit65** [comment]
I am still wondering why `Project-Id-Version` in mate-user-guide/mate-user-guide.pot looks like this with gettext?
 `"Project-Id-Version: PACKAGE VERSION\n"`

mate-user-guide.pot for /po folder looks like expected.
`"Project-Id-Version: mate-user-guide 1.23.0\n"`

**Review by selectiveduplicate — COMMENTED** [review]
The build passed on Travis, but with various ``Could not merge`` errors for several languages; I got the same warnings on my machine running Ubuntu MATE 18.04.2. I also got the same "fuzzy" warnings for the ``.po`` files; I'm not sure if they are really a problem here; aren't they supposed to be just diagnostic reports by ``msmerge``?

**Comment by selectiveduplicate** [comment]
> I am still wondering why `Project-Id-Version` in mate-user-guide/mate-user-guide.pot looks like this with gettext?
> `"Project-Id-Version: PACKAGE VERSION\n"`
> 
> mate-user-guide.pot for /po folder looks like expected.
> `"Project-Id-Version: mate-user-guide 1.23.0\n"`

@raveit65 
The value of ``Project-Id-Version`` is supposed to be guessed from a **configure** script; so in this case in /po folder there's a ``Makefile.in`` with package version ``1.23.0``, so the value is guessed right... but in the other case, we have ``PACKAGE_VERSION = @PACKAGE_VERSION@`` in our generated ``Makefile.in``; it doesn't match with the ``Makefile.in`` of /po folder. I think something needs to be changed in the ``configure.ac`` in the root folder or something else; I'm not sure...

**Comment by raveit65** [comment]
@selectiveduplicate 
merge issues are already fixed by 
https://github.com/mate-desktop/mate-user-guide/commit/291d3b7f97d0a3acafb68b12c58d3b6206c899f3
https://github.com/mate-desktop/mate-user-guide/commit/b649cf14b2387247fd43202d6ebd43bb5bb97227
https://github.com/mate-desktop/mate-user-guide/commit/0e7cd7d618394a40a8a6b5f7ed832b965fb9badc
https://github.com/mate-desktop/mate-user-guide/commit/298155be8377da1b46ef833e5d0af9bcbb0a132a
PR needs rebased.

**Comment by raveit65** [comment]
@selectiveduplicate 

> I also got the same "fuzzy" warnings for the .po files; 

@rbuj did already a comment about it in another package.
Don't know where it was....
Those warnings should be gone after a push and pull from transifex,...
.....i hope.

> The value of Project-Id-Version is supposed to be guessed from a configure script; so in this case in /po folder there's a Makefile.in with package version 1.23.0, so the value is guessed right... but in the other case, we have PACKAGE_VERSION = @PACKAGE_VERSION@ in our generated Makefile.in. I think something needs to be changed in the configure.ac in the root folder or something else; I'm not sure...

I am not really sure if gettext is used for mate-user-guide/mate-user-guide.pot ?

**Comment by selectiveduplicate** [comment]
@raveit65 
It should be used, judging by the main ``configure.ac`` and all the makefiles in mate-user-guide folder; but as per my observation the ``Makefile.in`` in mate-user-guide folder doesn't contain package version ``1.23.0`` but the po folder does...

Should we use ``mate-user-guide/Makefile.in`` instead of ``mate-user-guide/Makefile`` in ``configure.ac``?

**Comment by raveit65** [comment]
For me the build log looks different for /po and /mate-user-guide folder.
```
rm -f zh_CN.gmo && /usr/bin/msgfmt -c --statistics --verbose -o zh_CN.gmo zh_CN.po
rm -f zh_HK.gmo && /usr/bin/msgfmt -c --statistics --verbose -o zh_HK.gmo zh_HK.po
/usr/bin/msgfmt: zh_CN.po: warning: PO file header fuzzy
     /usr/bin/msgfmt: zh_HK.po: warning: PO file header fuzzy
                           warning: older versions of msgfmt will give an error on this
        zh_HK.po: 2 translated messages, 2 untranslated messages.
              warning: older versions of msgfmt will give an error on this
zh_CN.po: 2 translated messages, 2 untranslated messages.
rm -f zh_TW.gmo && /usr/bin/msgfmt -c --statistics --verbose -o zh_TW.gmo zh_TW.po
/usr/bin/msgfmt: zh_TW.po: warning: PO file header fuzzy
                           warning: older versions of msgfmt will give an error on this
zh_TW.po: 2 translated messages, 2 untranslated messages.
make[2]: Leaving directory '/rootdir/po'
touch stamp-po
make[1]: Leaving directory '/rootdir/po'
Making all in mate-user-guide
make[1]: Entering directory '/rootdir/mate-user-guide'
  GEN      ko/ko.mo
  GEN      bn/bn.mo
  GEN      zh_HK/zh_HK.mo
  GEN      de/de.mo
  GEN      gl/gl.mo
  GEN      ky/ky.mo
  GEN      zh_TW/zh_TW.mo
  GEN      zh_CN/zh_CN.mo
```

**Comment by yetist** [comment]
The documents for yelp didn't use gettext, it use itstools, so they are different:
https://gitlab.gnome.org/GNOME/yelp-tools/blob/master/tools/yelp.m4#L31
https://gitlab.gnome.org/GNOME/yelp-tools/blob/master/tools/yelp.m4#L72

**Comment by raveit65** [comment]
> The documents for yelp didn't use gettext, it use itstools, so they are different:

Ok, that makes it clear.

**Review by raveit65 — APPROVED** [review]
LGTM.
Thanks.

**Review by selectiveduplicate — APPROVED** [review]
> 
> 
> The documents for yelp didn't use gettext, it use itstools, so they are different:

Okay... then I guess everything's fine here! 🙂

**Pull request merged**
