### PR TITLE
Browser mode is the default in MATE

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Review by sc0w — COMMENTED** [review]
The image is larger than the others on the same page.

I suggest a smaller image

**Comment by lukefromdc** [comment]
This fixes a clear error left over from when GNOME 2 for a short time used spatial mode as the default, right about the time the very first version of Ubuntu came out I remember seeing this as the default. When it was changed this obviously was not changed to keep up

**Review by lukefromdc — COMMENTED** [review]
This works, but I confirm the image comes out almost twice the size of the others. That should be fixed if possible but we need this because spatial mode has never been the default in MATE even though it was in GNOME for a while

**Review by lukefromdc — APPROVED** [review]
Smaller image works, this is good to go

**Comment by raveit65** [comment]
I cherry-picked that 1.20, otherwise it isn't possible to use updates from transifex for 1.20 branch of mate-user-guide.
Can you please do that for yourself if you  merge fixes for user-guide translations?

**Comment by raveit65** [comment]
And mate-user-guide-content.pot is updated
https://github.com/mate-desktop/mate-user-guide/commit/8329f38401fe7695ddcab39e89e022620fca15f6
This can be done with
`./autogen.sh && ./makepot`

**Comment by lukefromdc** [comment]
OK, good to know. I know absolutely nothing about working with translations. Is it OK to merge and cherrypick, or should not merge anything else to m-u-g myself?

**Comment by raveit65** [comment]
MUG use only one branch (master) for transifex server, because we added translations for MUG after the 1.20 release in January.
All other packages use one *.pot file for master and 1.20 branch.

That means for mug:
We pull translations from transifex with `tx pull -a -f` command only for master, and we can cherry-pick that commit from master to 1.20.
The condition for that will work is that translation strings are the same in master and 1.20.
So merging and cherry-picking is fine for MUG.

When a commit change a translation string we need to re-generate the `mate-user-guide-content.pot` file with
`./autogen.sh && ./makepot`   
Now, commit the change and push it to github.
Transifex server will be updated automatic from github server when the commit is pushed.
You only have to make sure that these 2 lines at the beginning of `mate-user-guide-content.pot` looks like these, because of a issue with transifex.
```
"Project-Id-Version: MATE Desktop Environment\n"
"Content-Type: text/plain; charset=UTF-8\n"
```

Any way, it is OK for me to update the source file by myself. But chery-picking to 1.20 branch after a merge would be great.

**Pull request merged**
