### PR TITLE
Typos reported by translators

### PR DESCRIPTION
**Pull request by raveit65**
See at transifex for long list of reported typos.

### CODE REVIEW

**Review by lukefromdc — COMMENTED** [review]
One possible issue here:

Line 829:
-list to navigate to quickly return to these places. Your history list contains the last ten items that

+list to navigate quickly return to these places. Your history list contains the last ten items that

Probably should be something like

+list to navigate to or quickly return to these places. Your history list contains the last ten items that

**Comment by raveit65** [comment]
@lukefromdc 
Done

**Review by lukefromdc — APPROVED** [review]
Looks good to me

**Comment by usergreen** [comment]
Line 453 is correct, because there are plural buttons for zooming. So, no need to change.
--> <para><guimenu>Zoom</guimenu> buttons: Enable you to change the

Line 829 should be:
--> list to navigate to return quickly to these places. Your history list contains the last ten items that

The above is my suggestion.

**Pull request merged**
