### PR TITLE
Add Catalan screenshots

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by lukefromdc** [comment]
Not sure I can test this one, as I have all unused locales purged on my machine. Calling for review by rest of core team

**Review by lukefromdc — COMMENTED** [review]
While I cannot test other locales, opening Caja help in  default US locale works fine, and I see such images as the button bar, however these images also come up fine in master with my locale. Need a test by someone who can test this locale

**Comment by sc0w** [comment]
I have tested with:

`env LANG=ca_ES.UTF-8 yelp help:mate-user-guide`

...and I can see all the images in this PR.

**Review by sc0w — APPROVED** [review]

**Review by raveit65 — APPROVED** [review]
`make distcheck` runs fine.

**Comment by raveit65** [comment]
and cherry-picked to 1.20 816f751b0706ed18076766019b88c365c28f3f7b
@rbuj 
A big thank you for working on the guide :)

**Pull request merged**
