### PR TITLE
Remove extra char

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
Nice catch, this looks good to go

**Comment by lukefromdc** [comment]
The extra character looked rather nasty in actually pulling up the main menubar help. After dropping the new version of this this file into the relevent place it was gone. Merging this

**Comment by raveit65** [comment]
Can you please cherry-pick all changes to 1.20 after merging something to master ?

**Comment by lukefromdc** [comment]
Done with
https://github.com/mate-desktop/mate-user-guide/commit/6a21e178bfbb7ad3838738c997a72c68582b47b3

**Pull request merged**
