### PR TITLE
[ci] show help pages on website

### PR DESCRIPTION
**Pull request by yetist**
The html files are created.
https://github.com/mate-desktop/mate-user-guide/tree/gh-pages

### CODE REVIEW

**Comment by yetist** [comment]
@raveit65 

Need enable gh-pages, thank you.

**Comment by raveit65** [comment]
Done, the guide is at http://mate-desktop.github.io/mate-user-guide/

But why not at https://mate-user-guide.mate-desktop.dev/ ?
This link gives me currently a security warning from firefox.

**Comment by raveit65** [comment]
I will squash the last 2 commits.

**Comment by yetist** [comment]
Lost CNAME file, the last commit will do that.

**Comment by raveit65** [comment]
This looks better in repo settings.
```
Your site is ready to be published at http://mate-user-guide.mate-desktop.dev/.
```

**Review by rbuj — APPROVED** [review]
I can see the mate user guide at https://mate-user-guide.mate-desktop.dev/

**Review by raveit65 — APPROVED** [review]
LGTM,
the user-guide displays nice at gh-pages.

**Review by sc0w — APPROVED** [review]

**Review by selectiveduplicate — APPROVED** [review]
It works! :slightly_smiling_face:

**Pull request merged**
