### PR TITLE
added keyboard shortcut for showing hidden files

### PR DESCRIPTION
**Pull request by selectiveduplicate**

### CODE REVIEW

**Review by raveit65 — APPROVED** [review]
Nice idea and it works well.
Tested with `yelp "/usr/local/share/help/C/mate-user-guide/goscaja.xml"`
Thanks

**Review by lukefromdc — APPROVED** [review]
This works well and is a long-overdue addition

**Review by rbuj — APPROVED** [review]
Tested and approved.
<pre>git fetch upstream pull/23/head:add-keyboard-shortcut-for-showing-hidden-files
git checkout add-keyboard-shortcut-for-showing-hidden-files
./autogen.sh && make clean && make && sudo make install
yelp help:mate-user-guide/caja-managing-hidden-files</pre>

**Comment by raveit65** [comment]
I think 2 approvals are enough :) 
So, i will merge it and cherry-pick to 1.20 + update transifex source for master branch.

**Pull request merged**
