### PR TITLE
Show MATE logo in menu panel

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by sc0w** [comment]
Navigating in the documentation (`yelp help:mate-user-guide`), I can't see the image **menu_panel.png** with / without this PR.

**Comment by raveit65** [comment]
Should be save to remove menu_panel.png, it is only mentioned in changelog.
```
[rave@satellite mate-user-guide]$ grep -nr menu_panel.png mate-user-guide/C/
mate-user-guide/C/ChangeLog:792:	 * Updated screenshots: typical_anno_desktop.png, menu_panel.png, caja_prop_emblem_window.png, cc_theme_window_tab.png, 
[rave@satellite mate-user-guide]$ 
```

**Review by raveit65 — APPROVED** [review]
works fine, thank you

**Comment by raveit65** [comment]
@rbuj 
I tested it again and in
`env LANG=us_US.UTF-8 yelp help:mate-user-guide/gospanel-1`
i found gnome logo.
bildschirmfoto zu 2018-09-24 23-49-40
And were is new menu_bar_applet.png?

Edit:
Sorry, my mistake...

**Review by raveit65 — COMMENTED** [review]
see my previous comment

**Comment by raveit65** [comment]
Btw. i did a mistake which is fixed by https://github.com/mate-desktop/mate-user-guide/commit/f7d047aa8f433977cd10a5d16ca1c228008a20e3

**Comment by raveit65** [comment]
ohh, sorry all is fine 
It's to late, i will check it again

**Review by raveit65 — APPROVED** [review]

**Comment by rbuj** [comment]
Ok, don't worry ;-)

**Comment by raveit65** [comment]
Ok, i could solve my confusion , it was to late yesterday, sorry.
Of course the PR fix it only for C language. In other languages, e.g. German, you will see the old existing image.
So the PR is fine and ready to go.

**Comment by raveit65** [comment]
And cherry-picked to 1.20 branch.
Thank you-

**Pull request merged**
