### PR TITLE
Remove full stop (period) in title ending

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
I was only able to find one of the edits in reasonable time looking around the caja help., but it came up fine and I had no build or runtime issues with this

**Comment by raveit65** [comment]
@rbuj 
Can you please rebase the PR against master branch?
I can't pull it local.
```
[rave@satellite mate-user-guide]$ git checkout -b rbuj-title-ending-period master
Switched to a new branch 'rbuj-title-ending-period'
[rave@satellite mate-user-guide]$ git pull https://github.com/rbuj/mate-user-guide.git title-ending-period
From https://github.com/rbuj/mate-user-guide
 * branch            title-ending-period -> FETCH_HEAD
Auto-merging mate-user-guide/C/goscaja.xml
CONFLICT (content): Merge conflict in mate-user-guide/C/goscaja.xml
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by rbuj** [comment]
@raveit65 fixed

**Review by raveit65 — APPROVED** [review]
Build and runs fine. Also discheck is fine.
Thank you.

**Pull request merged**
