### PR TITLE
update reporting-bugs section

### PR DESCRIPTION
**Pull request by selectiveduplicate**

### CODE REVIEW

**Review by raveit65 — APPROVED** [review]
LGTM

**Review by rbuj — APPROVED** [review]

**Comment by vkareh** [comment]
@selectiveduplicate - can you use "Rebase and merge" for future commits? That way we don't pollute the git log with a bunch of unnecessary `Merge pull request #123 from foo/bar` messages.

Nothing particularly wrong with them, they just look ugly :stuck_out_tongue_winking_eye:

**Comment by selectiveduplicate** [comment]
> @selectiveduplicate - can you use "Rebase and merge" for future commits? That way we don't pollute the git log with a bunch of unnecessary `Merge pull request #123 from foo/bar` messages.
> 
> Nothing particularly wrong with them, they just look ugly stuck_out_tongue_winking_eye

I feared this mess might happen! I'll be sure to remember this in the future!
I actually forgot that this PR was unmerged so deleted the branch accidentally. Sorry for that!

**Comment by vkareh** [comment]
haha no worries, thanks! good thing github remembers :)

**Pull request merged**
