### PR TITLE
Fix spelling and grammar mistakes

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
While I cannot find most of the individual errors to be corrected here due to the volume of material in the help browser, this builds and runs fine, Caja help etc come up fine. Other PR's of this nature have all worked fine too. I did find and verify one of them, in the reference to Caja spatial windows so we know that part at least works as expected.

**Review by raveit65 — APPROVED** [review]
Should be sufficient to review the the changes by simply reading the file by a native American English speaker.
For me with my bad pidgin English it looks OK :)
Some strings were changed from UK to American English (behaviour ---> behavior).
I think xml language issues we will see in build logs, and distcheck runs fine.

Looks good so far.

**Comment by rbuj** [comment]
I did the spelling & grammar revision using LanguageTool:

$ java -Dfile.encoding=UTF-8 -jar ~/Documents/LanguageTool-4.2/languagetool-commandline.jar -l en-US -d EN_QUOTES,WHITESPACE_RULE,PUNCTUATION_PARAGRAPH_END,COMMA_PARENTHESIS_WHITESPACE --xmlfilter file.xml

**Comment by raveit65** [comment]
Nice tool. I can confirm that that running the tool doesn't show any issue which is fixed by this PR.
Ready to go.

**Comment by raveit65** [comment]
New source for transifex is generated and commited.
https://github.com/mate-desktop/mate-user-guide/commit/aaf51b507f40c14c8596412994f397ec179178a6

**Pull request merged**
