### PR TITLE
Remove unused screenshots

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Review by lukefromdc — COMMENTED** [review]
For some reason, this works when built from the the branch tarball, but matre-panel help fails when built from a pull and rebase against master. On the rebase against master I get 
```

Document Not Found
The URI ‘help:mate-user-guide/gospanel-1’ does not point to a valid page.
```

and got this on two different pulls and builds

**Comment by rbuj** [comment]
Because Makefile.am has been modified, you must first run the command ./autogen.sh, then make. If you want to install the manual on your system, sudo make install.

Test from the command line (after sudo make install):

[robert@localhost mate-user-guide]$ for test_case in hrefs links media validate comments; do echo "[ yelp-check $test_case ]"; yelp-check $test_case /usr/local/share/help/C/mate-user-guide/index.docbook; done

Test output:

[ yelp-check hrefs ]
feedback-docs: http://ml.mate-desktop.org/listinfo
filechooser-open-folder: help:engrampa
gospanel-17: help:mate-clock
gospanel-554: help:mate-search-tool
joinmate: http://live.gnome.org/JoinMate
legalnotice: help:fdl
overview-applications: help:eom
overview-applications: help:gucharmap
overview-applications: help:mate-dictionary
overview-applications: help:mate-terminal
overview-applications: help:pluma
places-menu: help:mate-search-tool
top-panel: help:mate-clock
yelp-joininggdp: http://wiki.mate-desktop.org/dev-doc:doc-team-guide?s[]=users[]=guide#mate_documentation_team
yelp-moreinfo: help:mate-doc-make
yelp-moreinfo: help:mate-doc-xslt
yelp-moreinfo: http://ml.mate-desktop.org/listinfo/mate-dev
[ yelp-check links ]
[ yelp-check media ]
[ yelp-check validate ]
[ yelp-check comments ]

yelp-check : https://wiki.gnome.org/Apps/Yelp/Tools/yelp-check

However, I agree some (h)refs are not valid, such as http://live.gnome.org/JoinMate, http://ml.mate-desktop.org/listinfo, http://ml.mate-desktop.org/listinfo/mate-dev, help:mate-doc-make, help:mate-doc-xslt... but it should be argued in another PR/RFE/ISSUE.

**Comment by lukefromdc** [comment]
I think I know what the problem is: on pulling this into my main repo, I get a merge commit, which also includes a Makefile change. Reverting the merge commit so it can be rebased must be killing the makefile change. I always start a build with ./autogen.sh since I am always building from git

**Comment by rbuj** [comment]
I can do a new PR if you prefer. Finally, I ran this script on FreeBSD:
<pre>
#!/bin/bash
for file in mate-user-guide/*/figures/*.png; \
do
  fbname=${file##*/}
  count=$(git grep $fbname | wc -l)
  if [ $count -lt 3 ]; \
  then
    find ./mate-user-guide -name $fbname -exec rm {} +
    echo "sed -i '' '/${fbname//./\\.}/d' ./mate-user-guide/Makefile.am" | sh
  fi
done
</pre>

**Comment by lukefromdc** [comment]
You could do that, or do a forced-update to the same branch splitting out the makefile change from that merge commit. Either should work fine.

**Comment by rbuj** [comment]
New PR #13

**Comment by lukefromdc** [comment]
OK, I see it. Will test it when I get back from an event tonight

**Pull request closed without merging**
